# Generated by Django 2.2.6 on 2019-11-05 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('steam_guard_name', models.CharField(max_length=200)),
                ('api_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.IntegerField()),
                ('classid', models.IntegerField()),
                ('instanceid', models.IntegerField()),
                ('appid', models.IntegerField()),
                ('descriptions', models.TextField()),
                ('owner_descriptions', models.TextField()),
                ('exterior', models.CharField(max_length=200)),
                ('icon_url', models.TextField()),
                ('market_hash_name', models.CharField(max_length=200)),
                ('market_mame', models.CharField(max_length=200)),
                ('marketable', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('tags', models.TextField()),
                ('tradable', models.IntegerField()),
                ('type', models.CharField(max_length=200)),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.Bot')),
            ],
        ),
    ]
