# Generated by Django 2.2.6 on 2019-11-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='link',
            field=models.CharField(max_length=200, null='steam url'),
            preserve_default='steam url',
        ),
    ]
